apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pfc
  template:
    metadata:
      labels:
        app: pfc
    spec:
      containers:
      - name: pfc
        image: umesh2645/pfc:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: pfc-service
spec:
  type: LoadBalancer
  selector:
    app: pfc
  ports:
  - name: http
    port: 3005
    targetPort: 3005